---
version: 2.1

orbs:
  github: circleci/github-cli@2

executors:
  build:
    parameters:
      arch:
        type: string
      tag:
        type: string
        default: jammy
      resource_class:
        type: string
    environment:
      TARGETARCH: << parameters.arch >>
      IN_CONTAINER: "true"
    docker:
      - image: buildpack-deps:<< parameters.tag >>
    resource_class: << parameters.resource_class >>

commands:
  push-artifacts:
    steps:
      - github/setup:
          version: "2.43.1"
      - run:
          name: Upload artifacts - $TARGETARCH
          command: >-
            gh release upload \
              "$CIRCLE_TAG" \
              ./dist/* \
              --repo "$(git config --get remote.origin.url)"

jobs:
  build:
    parameters:
      arch:
        type: string
      executor:
        type: string
        default: build
      resource_class:
        type: string
    executor:
      name: << parameters.executor >>
      arch: << parameters.arch >>
      resource_class: << parameters.resource_class >>
    steps:
      - checkout
      - run:
          name: Build
          command: ./build.sh


  draft-release:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - github/setup:
          version: "2.43.1"
      - checkout
      - run:
          name: Create draft release
          command: >-
            gh release create "${CIRCLE_TAG}"
            --draft
            --prerelease
            --generate-notes
            --verify-tag


workflows:
  tags:
    jobs:
      - draft-release:
          name: Create github release
          context: github
          filters: &filter-tags
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - build: &tag-build
          name: AMD64 tag release
          context: github
          arch: amd64
          resource_class: large
          filters: *filter-tags
          requires:
            - "Create github release"
          post-steps:
            - push-artifacts
      - build:
          <<: *tag-build
          name: ARM64 tag release
          arch: arm64
          resource_class: arm.large
