---
version: 2.1

orbs:
  docker: circleci/docker@3
  github: circleci/github-cli@2
  go: circleci/go@1

parameters:
  kernel_version:
    type: string
    default: "7.0.0"
  ubuntu_build:
    type: string
    default: "14"
  ubuntu_flavour:
    type: string
    default: "generic"
  ubuntu_name:
    type: string
    default: "resolute"
  abi_version:
    type: string
    default: "14"

commands:
  push-artifacts:
    steps:
      - github/setup:
          version: "2.43.1"
      - run:
          name: Upload artifacts - $TARGETARCH
          command: >-
            gh release upload
            "$CIRCLE_TAG"
            ./dist/*
            --repo "$(git config --get remote.origin.url)"

jobs:
  build:
    parameters:
      arch:
        type: string
        default: amd64
      resource_class:
        type: string
        default: xlarge
    docker:
      - image: cimg/base:current
    resource_class: <<parameters.resource_class>>
    environment:
      IMAGE_FQN: ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
      IMAGE_TAG: << pipeline.git.tag or pipeline.git.branch >>-<< parameters.arch >>
      REGISTRY: ghcr.io
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker_password: GITHUB_TOKEN
          docker_username: CIRCLE_PROJECT_USERNAME
          registry: ${REGISTRY}
      - docker/build:
          image: ${IMAGE_FQN}
          registry: ${REGISTRY}
          tag: ${IMAGE_TAG}
          use_buildkit: true
          cache_from: ${REGISTRY}/${IMAGE_FQN}:${IMAGE_TAG}
          extra_build_args: >-
            --build-arg BUILDKIT_INLINE_CACHE=1
            --build-arg KERNEL_VERSION=<< pipeline.parameters.kernel_version >>
            --build-arg UBUNTU_BUILD=<< pipeline.parameters.ubuntu_build >>
            --build-arg UBUNTU_FLAVOUR=<< pipeline.parameters.ubuntu_flavour >>
            --build-arg UBUNTU_NAME=<< pipeline.parameters.ubuntu_name >>
            --build-arg ABI_VERSION=<< pipeline.parameters.abi_version >>
            --target output
      - docker/push:
          image: ${IMAGE_FQN}
          registry: ${REGISTRY}
          tag: ${IMAGE_TAG}
      - run:
          name: collect artifacts
          environment:
            DCID: kernel_output
          command: |
            docker create --name "${DCID}" "${REGISTRY}/${IMAGE_FQN}:${IMAGE_TAG}"
            mkdir test-results
            docker cp "${DCID}":/output/results.xml test-results/
            mkdir dist
            docker cp "${DCID}":/boot/vmlinuz dist/
            docker cp -L "${DCID}":/usr/lib/modules - | gzip > dist/modules.tar.gz
            docker rm "${DCID}"
      - store_test_results:
          path: test-results


  draft-release:
    executor:
      name: go/default
      tag: "1.21"
    resource_class: small
    steps:
      - checkout
      - run:
          name: go-semantic-release
          command: |
            curl -sSL https://get-release.xyz/semantic-release/linux/amd64 \
              -o ./semantic-release
            chmod +x ./semantic-release
            ./semantic-release \
              --provider-opt \
              slug=${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} \
              --allow-no-changes \
              --prerelease \
              --allow-initial-development-versions

workflows:
  feature:
    jobs:
      - build: &amd64-build
          name: AMD64 feature build
          arch: amd64
          context: github
          filters: &filter-feature
            branches:
              ignore: master
            tags:
              ignore: /.*/
      - build: &arm64-build
          <<: *amd64-build
          name: ARM64 feature build
          arch: arm64
          resource_class: arm.xlarge


  release:
    jobs:
      - draft-release:
          name: Create github release
          context: github
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/

  tags:
    jobs:
      - build:
          <<: *amd64-build
          filters: &filter-tags
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          post-steps:
            - push-artifacts
      - build:
          <<: *arm64-build
          filters: *filter-tags
          post-steps:
            - push-artifacts
