---
version: 2.1

orbs:
  github: circleci/github-cli@2

executors:
  arm64:
    environment:
      TARGETARCH: arm64
      IN_CONTAINER: "true"
    docker:
      - image: buildpack-deps:jammy
    resource_class: petercb/arm64
  amd64:
    environment:
      TARGETARCH: amd64
      IN_CONTAINER: "true"
    docker:
      - image: buildpack-deps:jammy
    resource_class: petercb/amd64


commands:
  push-artifacts:
    steps:
      - github/setup:
          version: "2.43.1"
      - run:
          name: Upload artifacts - $TARGETARCH
          command: >-
            gh release upload \
              "$CIRCLE_TAG" \
              ./dist/* \
              --repo "$(git config --get remote.origin.url)"

jobs:
  build:
    parameters:
      executor:
        type: executor
        default: amd64
    executor: << parameters.executor >>
    steps:
      - checkout
      - run:
          name: Build
          command: ./build.sh


  draft-release:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - github/setup:
          version: "2.43.1"
      - checkout
      - run:
          name: Create draft release
          command: >-
            gh release create "${CIRCLE_TAG}"
            --draft
            --prerelease
            --generate-notes
            --verify-tag


workflows:
  continuous:
    jobs:
      - build:
          name: AMD64 RC build
          executor: amd64
      - build:
          name: ARM64 RC build
          executor: arm64

  tags:
    jobs:
      - draft-release:
          name: Create github release
          context: github
          filters: &filter-tags
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - build: &tag-build
          name: AMD64 tag release
          context: github
          executor: amd64
          filters: *filter-tags
          requires:
            - "Create github release"
          post-steps:
            - push-artifacts
      - build:
          <<: *tag-build
          name: ARM64 tag release
          executor: arm64
