---
version: 2.1

orbs:
  docker: circleci/docker@2
  github: circleci/github-cli@2

executors:
  build:
    parameters:
      arch:
        type: string
      resource_class:
        type: string
    environment:
      TARGETARCH: << parameters.arch >>
    docker:
      - image: ghcr.io/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}-builder:${CIRCLE_TAG}-<< parameters.arch >>
    resource_class: << parameters.resource_class >>


commands:
  push-artifacts:
    steps:
      - github/setup:
          version: "2.43.1"
      - run:
          name: Upload artifacts - $TARGETARCH
          command: >-
            gh release upload \
              "$CIRCLE_TAG" \
              ./dist/* \
              --repo "$(git config --get remote.origin.url)"


jobs:
  builder:
    parameters:
      arch:
        type: string
        default: amd64
      resource_class:
        type: string
        default: medium
    docker:
      - image: cimg/base:current
    resource_class: <<parameters.resource_class>>
    environment:
      IMAGE_FQN: ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}-builder
      IMAGE_TAG: ${CIRCLE_TAG}-<<parameters.arch>>
      REGISTRY: ghcr.io
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-password: GITHUB_TOKEN
          docker-username: CIRCLE_PROJECT_USERNAME
          registry: ${REGISTRY}
      - docker/build:
          image: ${IMAGE_FQN}
          registry: ${REGISTRY}
          tag: ${IMAGE_TAG}
          use-buildkit: true
          cache_from: ${IMAGE_FQN}:${IMAGE_TAG}
          extra_build_args: --build-arg BUILDKIT_INLINE_CACHE=1
      - docker/push:
          image: ${IMAGE_FQN}
          registry: ${REGISTRY}
          tag: ${IMAGE_TAG}

  build:
    parameters:
      arch:
        type: string
        default: amd64
      resource_class:
        type: string
        default: medium
    docker:
      - image: ghcr.io/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}-builder:${CIRCLE_TAG}-<<parameters.arch>>
        auth:
          username: ${CIRCLE_PROJECT_USERNAME}
          password: ${GITHUB_TOKEN}
    resource_class: <<parameters.resource_class>>
    steps:
      - checkout
      - run: ./build.sh

  draft-release:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - github/setup:
          version: "2.43.1"
      - checkout
      - run:
          name: Create draft release
          command: >-
            gh release create "${CIRCLE_TAG}"
            --draft
            --prerelease
            --generate-notes
            --verify-tag


workflows:
  tags:
    jobs:
      - builder: &tag-builder
          name: AMD64 builder
          context: github
          arch: amd64
          resource_class: medium
          filters: &filter-tags
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - builder:
          <<: *tag-builder
          name: ARM64 builder
          arch: arm64
          resource_class: arm.medium
          filters: *filter-tags
      - draft-release:
          name: Create github release
          context: github
          filters: *filter-tags
          requires:
            - "AMD64 builder"
            - "ARM64 builder"
      - build: &tag-build
          name: AMD64 tag release
          context: github
          arch: amd64
          resource_class: large
          filters: *filter-tags
          requires:
            - "Create github release"
          post-steps:
            - push-artifacts
      - build:
          <<: *tag-build
          name: ARM64 tag release
          arch: arm64
          resource_class: arm.large
